run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - bodyclose
    - noctx
    - sqlclosecheck
    - gocritic
    - gocyclo
    - misspell
    - unconvert
    - unparam

linters-settings:
  gosec:
    severity: medium
    confidence: high
  gocyclo:
    min-complexity: 15

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - bodyclose
    - path: _test\.go
      text: "SA5008"
    - path: .*\.pb\.go
      linters:
        - all
    - path: internal/mock/
      linters:
        - all
