name: 300-file-storage-ephemeral
services:
  app:
    build:
      context: ../../../..
      dockerfile: sdk-api/examples/300-file-storage/ephemeral/Dockerfile
    ports:
      - "23301:23301"
    environment:
      DOCKER_TEST: "1"
      RPS_BENCH: "${RPS_BENCH}"
      PORT: "23301"
