package handler

import (
	"auth-roles/internal/svc"
	"github.com/natuleadan/sdk-api/runtime"
)

func RegisterRestRoutes(s *runtime.Service, svcCtx *svc.ServiceContext) {
	s.WithRest("loginHandler", handleLogin(svcCtx))
	s.WithRest("signupHandler", handleSignup(svcCtx))
	s.WithRest("forgotPasswordHandler", handleForgotPassword(svcCtx))
	s.WithRest("resetPasswordHandler", handleResetPassword(svcCtx))
	s.WithRest("verifyEmailHandler", handleVerifyEmail(svcCtx))
	s.WithRest("mfaEnableHandler", handleMFAEnable(svcCtx))
	s.WithRest("mfaVerifyHandler", handleMFAVerify(svcCtx))
	s.WithRest("mfaProtectedHandler", handleMFAProtected(svcCtx))
	s.WithRest("changePasswordHandler", handleChangePassword(svcCtx))
	s.WithRest("revokeTokenHandler", handleRevokeToken(svcCtx))
	s.WithRest("blacklistProtectedHandler", handleBlacklistProtected(svcCtx))
	s.WithRest("noCSRFHandler", handleNoCSRF(svcCtx))
	s.WithRest("profileHandler", handleProfile(svcCtx))
	s.WithRest("listProducts", handleListProducts(svcCtx))
	s.WithRest("createProduct", handleCreateProduct(svcCtx))
	s.WithRest("getProduct", handleGetProduct(svcCtx))
	s.WithRest("updateProduct", handleUpdateProduct(svcCtx))
	s.WithRest("deleteProduct", handleDeleteProduct(svcCtx))
	s.WithRest("hardDeleteProduct", handleHardDeleteProduct(svcCtx))
	s.WithRest("setVisibility", handleSetVisibility(svcCtx))
	s.WithRest("getAuditLog", handleGetAuditLog(svcCtx))
	s.WithRest("listUsers", handleListUsers(svcCtx))
	s.WithRest("deleteUser", handleDeleteUser(svcCtx))
	s.WithRest("setUserRole", handleSetUserRole(svcCtx))
	s.WithRest("rateLimitedHandler", handleRateLimited(svcCtx))
	s.WithRest("perUserLimited", handlePerUserLimited(svcCtx))
	s.WithRest("perKeyLimited", handlePerKeyLimited(svcCtx))
	s.WithRest("perRoleLimited", handlePerRoleLimited(svcCtx))
	s.WithRest("viewerDataHandler", handleViewerData(svcCtx))
	s.WithRest("maxFuncLimited", handleMaxFuncLimited(svcCtx))
	s.WithRest("magicLink", handleMagicLink(svcCtx))
	s.WithRest("magicLinkVerify", handleMagicLinkVerify(svcCtx))
	s.WithRest("accessCode", handleAccessCode(svcCtx))
	s.WithRest("accessCodeVerify", handleAccessCodeVerify(svcCtx))
	s.WithRest("smsSend", handleSMSSend(svcCtx))
	s.WithRest("smsVerify", handleSMSVerify(svcCtx))
	s.WithRest("socialLogin", handleSocialLogin(svcCtx))
	s.WithRest("socialCallback", handleSocialCallback(svcCtx))
	s.WithRest("linkedAccounts", handleLinkedAccounts(svcCtx))
	s.WithRest("linkAccount", handleLinkAccount(svcCtx))
	s.WithRest("unlinkAccount", handleUnlinkAccount(svcCtx))
	s.WithRest("webAuthnRegisterBegin", handleWebAuthnRegisterBegin(svcCtx))
	s.WithRest("webAuthnRegisterFinish", handleWebAuthnRegisterFinish(svcCtx))
	s.WithRest("webAuthnLoginBegin", handleWebAuthnLoginBegin(svcCtx))
	s.WithRest("webAuthnLoginFinish", handleWebAuthnLoginFinish(svcCtx))
	s.WithRest("webAuthnManualLoginBegin", handleWebAuthnManualLoginBegin(svcCtx))
	s.WithRest("webAuthnManualLoginFinish", handleWebAuthnManualLoginFinish(svcCtx))
	s.WithRest("webAuthnCredentials", handleWebAuthnCredentials(svcCtx))
	s.WithRest("webAuthnDeleteCredential", handleWebAuthnDeleteCredential(svcCtx))
	s.WithRest("oidcDiscovery", handleOIDCDiscovery(svcCtx))
	s.WithRest("oidcJWKS", handleOIDCJWKS(svcCtx))
	s.WithRest("oidcUserInfo", handleOIDCUserInfo(svcCtx))
	s.WithRest("oauthAuthorize", handleOAuthAuthorize(svcCtx))
	s.WithRest("oauthToken", handleOAuthToken(svcCtx))
	s.WithRest("oauthIntrospect", handleOAuthIntrospect(svcCtx))
	s.WithRest("oauthRevoke", handleOAuthRevoke(svcCtx))
	s.WithRest("oauthClientsList", handleOAuthClientsList(svcCtx))
	s.WithRest("oauthClientsCreate", handleOAuthClientsCreate(svcCtx))
	s.WithRest("oauthClientsDelete", handleOAuthClientsDelete(svcCtx))
}
