name: kv-only-bench
services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    command: ["--cluster_mode=emulated"]

  bench:
    build:
      context: ../../../..
      dockerfile: sdk-api/examples/200-url-shortener/kv-dragonfly/Dockerfile
    ports:
      - "23204:23204"
    depends_on:
      dragonfly:
        condition: service_started
    environment:
      DOCKER_TEST: "1"
      DRAGONFLY_ADDR: dragonfly:6379
