// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: url_service.proto

package urlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShortCode     string                 `protobuf:"bytes,2,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	TargetUrl     string                 `protobuf:"bytes,3,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_url_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_url_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_url_service_proto_rawDescGZIP(), []int{0}
}

func (x *Link) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Link) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *Link) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *Link) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUrl     string                 `protobuf:"bytes,1,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkRequest) Reset() {
	*x = CreateLinkRequest{}
	mi := &file_url_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkRequest) ProtoMessage() {}

func (x *CreateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateLinkRequest) Descriptor() ([]byte, []int) {
	return file_url_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLinkRequest) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *CreateLinkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateLinkRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *Link                  `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkResponse) Reset() {
	*x = CreateLinkResponse{}
	mi := &file_url_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkResponse) ProtoMessage() {}

func (x *CreateLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateLinkResponse) Descriptor() ([]byte, []int) {
	return file_url_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLinkResponse) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

func (x *CreateLinkResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CreateLinkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExpandLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandLinkRequest) Reset() {
	*x = ExpandLinkRequest{}
	mi := &file_url_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandLinkRequest) ProtoMessage() {}

func (x *ExpandLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandLinkRequest.ProtoReflect.Descriptor instead.
func (*ExpandLinkRequest) Descriptor() ([]byte, []int) {
	return file_url_service_proto_rawDescGZIP(), []int{3}
}

func (x *ExpandLinkRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type ExpandLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUrl     string                 `protobuf:"bytes,1,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandLinkResponse) Reset() {
	*x = ExpandLinkResponse{}
	mi := &file_url_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandLinkResponse) ProtoMessage() {}

func (x *ExpandLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandLinkResponse.ProtoReflect.Descriptor instead.
func (*ExpandLinkResponse) Descriptor() ([]byte, []int) {
	return file_url_service_proto_rawDescGZIP(), []int{4}
}

func (x *ExpandLinkResponse) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *ExpandLinkResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_url_service_proto protoreflect.FileDescriptor

const file_url_service_proto_rawDesc = "" +
	"\n" +
	"\x11url_service.proto\x12\x06urlsvc\"m\n" +
	"\x04Link\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"short_code\x18\x02 \x01(\tR\tshortCode\x12\x1d\n" +
	"\n" +
	"target_url\x18\x03 \x01(\tR\ttargetUrl\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"a\n" +
	"\x11CreateLinkRequest\x12\x1d\n" +
	"\n" +
	"target_url\x18\x01 \x01(\tR\ttargetUrl\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\\\n" +
	"\x12CreateLinkResponse\x12 \n" +
	"\x04link\x18\x01 \x01(\v2\f.urlsvc.LinkR\x04link\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"2\n" +
	"\x11ExpandLinkRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\"C\n" +
	"\x12ExpandLinkResponse\x12\x1d\n" +
	"\n" +
	"target_url\x18\x01 \x01(\tR\ttargetUrl\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok2\x97\x01\n" +
	"\vLinkService\x12C\n" +
	"\n" +
	"CreateLink\x12\x19.urlsvc.CreateLinkRequest\x1a\x1a.urlsvc.CreateLinkResponse\x12C\n" +
	"\n" +
	"ExpandLink\x12\x19.urlsvc.ExpandLinkRequest\x1a\x1a.urlsvc.ExpandLinkResponseB\x13Z\x11600-grpc/pb/urlpbb\x06proto3"

var (
	file_url_service_proto_rawDescOnce sync.Once
	file_url_service_proto_rawDescData []byte
)

func file_url_service_proto_rawDescGZIP() []byte {
	file_url_service_proto_rawDescOnce.Do(func() {
		file_url_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_url_service_proto_rawDesc), len(file_url_service_proto_rawDesc)))
	})
	return file_url_service_proto_rawDescData
}

var file_url_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_url_service_proto_goTypes = []any{
	(*Link)(nil),               // 0: urlsvc.Link
	(*CreateLinkRequest)(nil),  // 1: urlsvc.CreateLinkRequest
	(*CreateLinkResponse)(nil), // 2: urlsvc.CreateLinkResponse
	(*ExpandLinkRequest)(nil),  // 3: urlsvc.ExpandLinkRequest
	(*ExpandLinkResponse)(nil), // 4: urlsvc.ExpandLinkResponse
}
var file_url_service_proto_depIdxs = []int32{
	0, // 0: urlsvc.CreateLinkResponse.link:type_name -> urlsvc.Link
	1, // 1: urlsvc.LinkService.CreateLink:input_type -> urlsvc.CreateLinkRequest
	3, // 2: urlsvc.LinkService.ExpandLink:input_type -> urlsvc.ExpandLinkRequest
	2, // 3: urlsvc.LinkService.CreateLink:output_type -> urlsvc.CreateLinkResponse
	4, // 4: urlsvc.LinkService.ExpandLink:output_type -> urlsvc.ExpandLinkResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_url_service_proto_init() }
func file_url_service_proto_init() {
	if File_url_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_url_service_proto_rawDesc), len(file_url_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_url_service_proto_goTypes,
		DependencyIndexes: file_url_service_proto_depIdxs,
		MessageInfos:      file_url_service_proto_msgTypes,
	}.Build()
	File_url_service_proto = out.File
	file_url_service_proto_goTypes = nil
	file_url_service_proto_depIdxs = nil
}
