// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: transfer_service.proto

package transferpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transfer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromAccount    string                 `protobuf:"bytes,2,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount      string                 `protobuf:"bytes,3,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	Amount         float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency       string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_transfer_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_transfer_service_proto_rawDescGZIP(), []int{0}
}

func (x *Transfer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transfer) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *Transfer) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *Transfer) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transfer) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Transfer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transfer) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Transfer) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type InitiateTransferRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FromAccount    string                 `protobuf:"bytes,1,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount      string                 `protobuf:"bytes,2,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	Amount         float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency       string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitiateTransferRequest) Reset() {
	*x = InitiateTransferRequest{}
	mi := &file_transfer_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateTransferRequest) ProtoMessage() {}

func (x *InitiateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateTransferRequest.ProtoReflect.Descriptor instead.
func (*InitiateTransferRequest) Descriptor() ([]byte, []int) {
	return file_transfer_service_proto_rawDescGZIP(), []int{1}
}

func (x *InitiateTransferRequest) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *InitiateTransferRequest) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *InitiateTransferRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *InitiateTransferRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *InitiateTransferRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type InitiateTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfer      *Transfer              `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateTransferResponse) Reset() {
	*x = InitiateTransferResponse{}
	mi := &file_transfer_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateTransferResponse) ProtoMessage() {}

func (x *InitiateTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateTransferResponse.ProtoReflect.Descriptor instead.
func (*InitiateTransferResponse) Descriptor() ([]byte, []int) {
	return file_transfer_service_proto_rawDescGZIP(), []int{2}
}

func (x *InitiateTransferResponse) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *InitiateTransferResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *InitiateTransferResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransferRequest) Reset() {
	*x = GetTransferRequest{}
	mi := &file_transfer_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferRequest) ProtoMessage() {}

func (x *GetTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferRequest.ProtoReflect.Descriptor instead.
func (*GetTransferRequest) Descriptor() ([]byte, []int) {
	return file_transfer_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

type GetTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfer      *Transfer              `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransferResponse) Reset() {
	*x = GetTransferResponse{}
	mi := &file_transfer_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferResponse) ProtoMessage() {}

func (x *GetTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferResponse.ProtoReflect.Descriptor instead.
func (*GetTransferResponse) Descriptor() ([]byte, []int) {
	return file_transfer_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransferResponse) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *GetTransferResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_transfer_service_proto protoreflect.FileDescriptor

const file_transfer_service_proto_rawDesc = "" +
	"\n" +
	"\x16transfer_service.proto\x12\vtransfersvc\"\xf0\x01\n" +
	"\bTransfer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\ffrom_account\x18\x02 \x01(\tR\vfromAccount\x12\x1d\n" +
	"\n" +
	"to_account\x18\x03 \x01(\tR\ttoAccount\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\xb8\x01\n" +
	"\x17InitiateTransferRequest\x12!\n" +
	"\ffrom_account\x18\x01 \x01(\tR\vfromAccount\x12\x1d\n" +
	"\n" +
	"to_account\x18\x02 \x01(\tR\ttoAccount\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"s\n" +
	"\x18InitiateTransferResponse\x121\n" +
	"\btransfer\x18\x01 \x01(\v2\x15.transfersvc.TransferR\btransfer\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"5\n" +
	"\x12GetTransferRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\"X\n" +
	"\x13GetTransferResponse\x121\n" +
	"\btransfer\x18\x01 \x01(\v2\x15.transfersvc.TransferR\btransfer\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok2\xc4\x01\n" +
	"\x0fTransferService\x12_\n" +
	"\x10InitiateTransfer\x12$.transfersvc.InitiateTransferRequest\x1a%.transfersvc.InitiateTransferResponse\x12P\n" +
	"\vGetTransfer\x12\x1f.transfersvc.GetTransferRequest\x1a .transfersvc.GetTransferResponseB\x18Z\x16600-grpc/pb/transferpbb\x06proto3"

var (
	file_transfer_service_proto_rawDescOnce sync.Once
	file_transfer_service_proto_rawDescData []byte
)

func file_transfer_service_proto_rawDescGZIP() []byte {
	file_transfer_service_proto_rawDescOnce.Do(func() {
		file_transfer_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transfer_service_proto_rawDesc), len(file_transfer_service_proto_rawDesc)))
	})
	return file_transfer_service_proto_rawDescData
}

var file_transfer_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_transfer_service_proto_goTypes = []any{
	(*Transfer)(nil),                 // 0: transfersvc.Transfer
	(*InitiateTransferRequest)(nil),  // 1: transfersvc.InitiateTransferRequest
	(*InitiateTransferResponse)(nil), // 2: transfersvc.InitiateTransferResponse
	(*GetTransferRequest)(nil),       // 3: transfersvc.GetTransferRequest
	(*GetTransferResponse)(nil),      // 4: transfersvc.GetTransferResponse
}
var file_transfer_service_proto_depIdxs = []int32{
	0, // 0: transfersvc.InitiateTransferResponse.transfer:type_name -> transfersvc.Transfer
	0, // 1: transfersvc.GetTransferResponse.transfer:type_name -> transfersvc.Transfer
	1, // 2: transfersvc.TransferService.InitiateTransfer:input_type -> transfersvc.InitiateTransferRequest
	3, // 3: transfersvc.TransferService.GetTransfer:input_type -> transfersvc.GetTransferRequest
	2, // 4: transfersvc.TransferService.InitiateTransfer:output_type -> transfersvc.InitiateTransferResponse
	4, // 5: transfersvc.TransferService.GetTransfer:output_type -> transfersvc.GetTransferResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_transfer_service_proto_init() }
func file_transfer_service_proto_init() {
	if File_transfer_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transfer_service_proto_rawDesc), len(file_transfer_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transfer_service_proto_goTypes,
		DependencyIndexes: file_transfer_service_proto_depIdxs,
		MessageInfos:      file_transfer_service_proto_msgTypes,
	}.Build()
	File_transfer_service_proto = out.File
	file_transfer_service_proto_goTypes = nil
	file_transfer_service_proto_depIdxs = nil
}
