name: products-service
port: 13002
api_prefix: /api/v1

auth:
  driver: none

entry:
  - type: crud
    path: /products
    model: Product
    auth: false
    db: main

databases:
  - name: main
    url: "${DATABASE_URL:-postgres://postgres:postgres@localhost:15433/postgres?sslmode=disable}"
    driver: postgres
    pool:
      max_conns: 500
      min_conns: 10

server:
  host: "0.0.0.0"
  max_conns: 10000
  timeout: 30s
